// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Client struct {
	ClientID    string  `json:"clientID"`
	UserName    string  `json:"userName"`
	Password    string  `json:"password"`
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	PhoneNumber string  `json:"phoneNumber"`
	Gender      *string `json:"gender"`
}

type Login struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type NewClient struct {
	UserName    string  `json:"userName"`
	Password    string  `json:"password"`
	FirstName   string  `json:"firstName"`
	LastName    string  `json:"lastName"`
	Gender      *string `json:"gender"`
	PhoneNumber string  `json:"phoneNumber"`
}

type Response struct {
	Error string `json:"error"`
}
