// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphqltest

type Client struct {
	ClientID    string `json:"clientID"`
	UserName    string `json:"userName"`
	Password    string `json:"password"`
	FullName    string `json:"fullName"`
	Gender      *bool  `json:"gender"`
	PhoneNumber string `json:"phoneNumber"`
}

type NewClient struct {
	UserName    string `json:"userName"`
	Password    string `json:"password"`
	FullName    string `json:"fullName"`
	Gender      *bool  `json:"gender"`
	PhoneNumber string `json:"phoneNumber"`
}
